version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
    - "5432:5432"
  web:
    build: ./BE
    container_name: backend
    command: python manage.py runserver --noreload --nothreading 0.0.0.0:8000
    ports:
      - "8000:8000"
      - "3000-3020:3000-3020"
    environment:
      - PYTHONUNBUFFERED=0
      - DJANGO_DEBUGGER=True
    depends_on:
      - db
